CREATE PROC FI_SP_IncluirBeneficiario
    @NOME          VARCHAR (50) ,
    @CPF           NVARCHAR (14) ,
	@IDCLIENTE     BIGINT
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END